spring:
  datasource:
    username: pguser
    password: pass9
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/credit_db

  liquibase:
    change-log: classpath:db/migrations.yaml