server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ekrylovich/spring-superbank/tree/main/technical/configurations
          default-label: main