server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: file://Users/egork/workspace/spring-course-td/configuration
          default-label: master

---
spring:
  profiles:
    active: docker
  cloud:
    config:
      server:
        git:
          uri: http://github.com/blablabla