server:
  port: 0

spring:
  application:
    name: credit-service
  profiles:
    active: dev

  datasource:
    username: pguser
    password: pass9
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/credit_db

  liquibase:
    change-log: classpath:db/migrations.yaml

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

topics:
  overdue:
    name: t.credit.overdue


---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

credit:
  rate:
    fixed: 0.05
    floating: 0.02



---
spring:
  config:
    activate:
      on-profile: prod
credit:
  rateProvider: http://localhost:8889/api/v1/rate