spring:
  application:
    name: credit-service

  config:
    import: optional:configserver:http://localhost:8888/

---
spring:
  profiles:
    active: docker
  config:
    import: optional:configserver:http://config:8888/
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/superbank-realm/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://postgres:5432/credit_db
  kafka:
    bootstrap-servers: kafka:9092

server:
  port:8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka